[tool.poetry]
name = "code"
version = "0.1.0"
description = ""
authors = ["ngelechei.kiprop <ngelechei.kiprop@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
netmiko = "^4.7.0"
junos-eznc = "^2.8.2"
requests = "^2.34.2"
xmltodict = "^1.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
